"""

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17FkR0d_YCycPVOWyI_jsuWMw2GZq8Tnp
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("salaries(1).csv")

df.head()

df.head(10)

df.tail(5)

input=df.drop('family_history',axis='columns')
input

target=df['family_history']
target

from sklearn.preprocessing import LabelEncoder

from sklearn.preprocessing import LabelEncoder

le_age = LabelEncoder()
le_bmi = LabelEncoder()

input['age_group_n'] = le_age.fit_transform(input['age_group'])
input['bmi_category_n'] = le_bmi.fit_transform(input['bmi_category'])

input.head()

input

input_n = input.drop(['age_group', 'bmi_category'], axis='columns')
input_n

target

from sklearn import tree
model=tree.DecisionTreeClassifier()

input_n.dtypes

le_glucose = LabelEncoder()

input_n['glucose_level_n'] = le_glucose.fit_transform(input_n['glucose_level'])

input_n = input_n.drop('glucose_level', axis=1)

input_n.dtypes

X = input_n.drop('has_diabetes', axis=1)
y = input_n['has_diabetes']

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X, y)

import pandas as pd

# نفس ترتيب الأعمدة اللي الموديل اتدرّب بيها
input_data = [[2, 1, 0]]
input_df = pd.DataFrame(input_data, columns=['age_group_n', 'bmi_category_n', 'glucose_level_n'])

# التنبؤ
prediction = model.predict(input_df)
print("Prediction:", prediction)

import pandas as pd

input_data = [[2, 1, 1]]
input_df = pd.DataFrame(input_data, columns=['age_group_n', 'bmi_category_n', 'glucose_level_n'])


prediction = model.predict(input_df)
print("Prediction:", prediction)